### PR TITLE
Feat/passio nutritionai searh

### PR DESCRIPTION
**Pull request by ivyas21**
### Description
We propose adding a new tool to the `community` package, enabling integration with Passio Nutrition AI for food search functionality. This tool will provide a simple interface for retrieving nutrition facts through the Passio Nutrition AI API, simplifying user access to nutrition data based on food search queries.

### Implementation Details
- **Class Structure:** Implement `NutritionAI`, extending `BaseTool`. It includes an `_run` method that accepts a query string and, optionally, a `CallbackManagerForToolRun`.
- **API Integration:** Use `NutritionAIAPI` for the API wrapper, encapsulating all interactions with the Passio Nutrition AI and providing a clean API interface.
- **Error Handling:** Implement comprehensive error handling for API request failures.

### Expected Outcome
- **User Benefits:** Enable easy querying of nutrition facts from Passio Nutrition AI, enhancing the utility of the `langchain_community` package for nutrition-related projects.
- **Functionality:** Provide a straightforward method for integrating nutrition information retrieval into users' applications.

### Dependencies
- `langchain_core` for base tooling support
- `pydantic` for data validation and settings management
- Consider `requests` or another HTTP client library if not covered by `NutritionAIAPI`.

### Tests and Documentation
- **Unit Tests:** Include tests that mock network interactions to ensure tool reliability without external API dependency.
- **Documentation:** Create an example notebook in `docs/docs/integrations/tools/passio_nutritionai.ipynb` showing usage, setup, and example queries.

### Contribution Guidelines Compliance
- Adhere to the project's linting and formatting standards (`make format`, `make lint`, `make test`).
- Ensure compliance with LangChain's contribution guidelines, particularly around dependency management and package modifications.

### Additional Notes
- Aim for the tool to be a lightweight, focused addition, not introducing significant new dependencies or complexity.
- Potential future enhancements could include caching for common queries to improve performance.

### Twitter Handle
[Optional] If you'd like a mention when this feature is announced, please include your Twitter handle. We can add our passio twitter handle.

This is above same format we can send it to PR to langchain community.

### CODE REVIEW

**Comment by ivyas21** [comment]
## Require installation and setup. 

I used `Python3.12` env. 

cd PROJECT_ROOT && python -m venv .venv && source .venv/bin/activate

pip install langchain
pip install python-dotenv

**Comment by kells1986** [comment]
I think this looks really good. There are just two things that I think we should think about before merging and running a PR upstream:
1. Does the tool work in an actual chain or agent? Please can you setup a simple agent that includes this tool in the demo notebook? For instance it could be an agent that takes conversational input like "I had bacon and eggs for breakfast" and then returns that nutritional profile of the meal, something like that. 
Ideally our tool improves these kind of agents and grounds the data in the real world, but we need to verify this.
Wolfram have a great GIF for this. There's a side-by-side image of a GPT with access to Wolfram and one without. The same question is asked to both, and the one with access to Wolfram Alpha generates a much nicer answer. That's a goal for this tool.
2. Minor, but naming. Ishani mentioned it in her video, but do we want `passio_nutritionai`, `passio_nutrition_ai`, `nutrition_ai` or some other variant? @drstarson what do you think? I think we should keep nutrition AI in the module name so it's clear to people who are making a food-related tool that this might be helpful. Maybe we should drop the `passio` part to keep it short?

**Comment by ivyas21** [comment]
I renamed to `passio_nutrition_ai`. I've done some testing.

FYI @kells1986 , @drstarson

**Comment by ivyas21** [comment]
@kells1986 After your review, I'll push it to PR to Upstream tomorrow morning.

**Pull request merged**
